<a href="https://colab.research.google.com/github/binharseneuit/IntroToML/blob/main/ML107/IntroToPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to Tensors
You can think of PyTorch tensors as fancy NumPy arrays, designed for use in neural networks. As you can see below, they share many of their basic operations with NumPy.

In [2]:
import torch
import numpy as np

# Think of tensors as NumPy arrays with some NN-friendly bells and whistles.
numpy_vector = np.array([1,2,3,4])
pytorch_vector = torch.tensor([1,2,3,4])
print(numpy_vector)
print(pytorch_vector)

[1 2 3 4]
tensor([1, 2, 3, 4])


In [3]:
# You can access their shapes the same way.
print(numpy_vector.shape)
print(pytorch_vector.shape)

(4,)
torch.Size([4])


In [4]:
# Creating matrices is the same, too.
numpy_matrix = np.array([[1,2],[3,4]])
pytorch_matrix = torch.tensor([[1,2],[3,4]])
print(numpy_matrix)
print(pytorch_matrix)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


Let's make a three dimensional tensor.

In [5]:
numpy_3d_tensor = np.array([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]], [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
pytorch_3d_tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]], [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(numpy_3d_tensor)
print(pytorch_3d_tensor)

[[[1 2 3]
  [3 6 9]
  [2 4 5]]

 [[1 2 3]
  [3 6 9]
  [2 4 5]]]
tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])


# Using the GPU

In [6]:
torch.cuda.is_available()

True

In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [8]:
tensor = torch.tensor([1,2,3])
device_tensor = tensor.to(device)
print(f"{device_tensor} is running on {device_tensor.device}")

tensor([1, 2, 3], device='cuda:0') is running on cuda:0


# Tensor Data Types
The complete list of PyTorch data types can be found [here](https://pytorch.org/docs/stable/tensors.html#data-types).

In [9]:
float32 = torch.tensor([1,2], dtype=torch.float32)
print(float32)
float32.dtype

tensor([1., 2.])


torch.float32

In [11]:
complex64 = torch.tensor([1,2], dtype=torch.complex64)
print(complex64)
complex64.dtype

tensor([1.+0.j, 2.+0.j])


torch.complex64

In [13]:
int16 = torch.tensor([1,2], dtype=torch.int16)
print(int16)
int16.dtype

tensor([1, 2], dtype=torch.int16)


torch.int16

# Multiplication

In [14]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [14, 2]])

# uncomment the line below and execute. how do you fix it?
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

# Reshaping

In [15]:
# tensors can also be reshaped with the following methods

shapable_tensor = torch.tensor([[1,2,3,4,5], [6,7,8,9,10]])
print(shapable_tensor.reshape(5,2))
print(shapable_tensor.reshape(10,1))

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])
tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])


# Intro to Autograd

Remember in the last lesson when we said automatic differentiation was the secret sauce of PyTorch? It's commonly called autograd (automatic gradient), and it's described below.

In [18]:
# Make a normal tensor, but specify the argument below
autograd_tensor = torch.tensor([3.0], requires_grad=True) # defaults to False
x = autograd_tensor
print(x)

tensor([3.], requires_grad=True)


Autograd keeps track of the operations performed on this tensor, simplifying the calculation of the derivative when it's time to perform gradient descent.

They're sort of like breadcrumbs that PyTorch leaves for itself as the neural net propagates forward, such that it can easily find all the derivatives during backpropagation by following those breadcrumbs back to their source.

In [19]:
y = x - 5
z = y * 3
a = (z**2)
y.retain_grad()
z.retain_grad()
a.retain_grad()
a.backward()

print(f"x is {x}")
print(f"y is {y}")
print(f"z is {z}")
print(f"a is {a}")
print("gradient of x is", x.grad)
print("gradient of y is", y.grad)
print("gradient of z is", z.grad)

x is tensor([3.], requires_grad=True)
y is tensor([-2.], grad_fn=<SubBackward0>)
z is tensor([-6.], grad_fn=<MulBackward0>)
a is tensor([36.], grad_fn=<PowBackward0>)
gradient of x is tensor([-36.])
gradient of y is tensor([-36.])
gradient of z is tensor([-12.])


In [20]:
rand_w = torch.randn(1, requires_grad=True)
rand_b = torch.randn(1, requires_grad=True)

# A Very Simple Example

In [22]:
x = torch.tensor([1.0])
y = torch.tensor([4.0])

torch.manual_seed(42)
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# update weight via gradient descent
for i in range(10):
  y_hat = w * x + b
  cost = ((y_hat - y)**2)
  print(f"~~for epoch {i+1}~~~")
  print("cost:", round(cost.item(),4))
  cost.backward()
  print(w, b, w.grad, b.grad)
  with torch.no_grad():
    w -= 0.1 * w.grad
    b -= 0.1 * b.grad
  w.grad.zero_()
  b.grad.zero_()

print(f"w value is {w.item()}, b value is {b.item()}")

~~for epoch 1~~~
cost: 12.4927
tensor([0.3367], requires_grad=True) tensor([0.1288], requires_grad=True) tensor([-7.0690]) tensor([-7.0690])
~~for epoch 2~~~
cost: 4.4974
tensor([1.0436], requires_grad=True) tensor([0.8357], requires_grad=True) tensor([-4.2414]) tensor([-4.2414])
~~for epoch 3~~~
cost: 1.6191
tensor([1.4677], requires_grad=True) tensor([1.2598], requires_grad=True) tensor([-2.5448]) tensor([-2.5448])
~~for epoch 4~~~
cost: 0.5829
tensor([1.7222], requires_grad=True) tensor([1.5143], requires_grad=True) tensor([-1.5269]) tensor([-1.5269])
~~for epoch 5~~~
cost: 0.2098
tensor([1.8749], requires_grad=True) tensor([1.6670], requires_grad=True) tensor([-0.9161]) tensor([-0.9161])
~~for epoch 6~~~
cost: 0.0755
tensor([1.9665], requires_grad=True) tensor([1.7586], requires_grad=True) tensor([-0.5497]) tensor([-0.5497])
~~for epoch 7~~~
cost: 0.0272
tensor([2.0215], requires_grad=True) tensor([1.8136], requires_grad=True) tensor([-0.3298]) tensor([-0.3298])
~~for epoch 8~~~
co

# Loss Functions and Optimizers

In [23]:
# first import neural net module
import torch.nn as nn

x = torch.tensor([1.0])
y = torch.tensor([4.0])

torch.manual_seed(42)
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

cost = nn.MSELoss()
# update weight via gradient descent
for i in range(10):
  y_hat = w * x + b
  c = cost(y, y_hat)
  optimizer = torch.optim.SGD([w, b], lr=0.1)
  print(f"~~for epoch {i+1}~~~")
  print("cost:", round(cost(y, y_hat).item(),4))
  c.backward()
  optimizer.step()
  optimizer.zero_grad()

print(f"w value is {w.item()}, b value is {b.item()}")

~~for epoch 1~~~
cost: 12.4927
~~for epoch 2~~~
cost: 4.4974
~~for epoch 3~~~
cost: 1.6191
~~for epoch 4~~~
cost: 0.5829
~~for epoch 5~~~
cost: 0.2098
~~for epoch 6~~~
cost: 0.0755
~~for epoch 7~~~
cost: 0.0272
~~for epoch 8~~~
cost: 0.0098
~~for epoch 9~~~
cost: 0.0035
~~for epoch 10~~~
cost: 0.0013
w value is 2.093254804611206, b value is 1.885373592376709
